title: frontend algorithm{
    near: top-center
    shape: text
    style: {
      font-size: 29
      bold: true
    }
  }

QuestionPages: {
    typea
    typeb
    typc
}
intro->QuestionPages->final