title: question data moving route(simple){
    near: top-center
    shape: text
    style: {
      font-size: 29
      bold: true
    }
  }
csvData->readingCsv&nextQuestion:bring csv data and processing them to read

readingCsv&nextQuestion<->QuestionPages
readingCsv&nextQuestion<->App
readingCsv&nextQuestion<->Common
QuestionPages->Typea,b,c: giving only question type
explanation: |md
  **ReadingCsv** is actived only at first.   
  then **nextQuestion** is actived at all-time(expect first).
|



